/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Test */
        get: operations["test_api__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/nfc/auth": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Nfc Auth */
        post: operations["nfc_auth_api_nfc_auth_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/nfc/provision": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Provision */
        post: operations["provision_api_nfc_provision_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/nfc/{haj_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Check Nfc */
        get: operations["check_nfc_api_nfc__haj_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/hajs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Hajs */
        get: operations["list_hajs_api_hajs_get"];
        put?: never;
        /** Add Haj */
        post: operations["add_haj_api_hajs_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/hajs/{haj_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Haj Info */
        get: operations["haj_info_api_hajs__haj_id__get"];
        put?: never;
        post?: never;
        /** Delete Haj */
        delete: operations["delete_haj_api_hajs__haj_id__delete"];
        options?: never;
        head?: never;
        /** Patch Haj */
        patch: operations["patch_haj_api_hajs__haj_id__patch"];
        trace?: never;
    };
    "/api/hajs/{haj_id}/image": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Haj Image */
        get: operations["get_haj_image_api_hajs__haj_id__image_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/hajs/{haj_id}/pfp": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Haj Pfp */
        get: operations["get_haj_pfp_api_hajs__haj_id__pfp_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/hajs/{haj_id}/posts": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Posts */
        get: operations["get_posts_api_hajs__haj_id__posts_get"];
        put?: never;
        /** Make Post */
        post: operations["make_post_api_hajs__haj_id__posts_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/hajs/{haj_id}/posts/{post_id}/image": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Post Image */
        get: operations["get_post_image_api_hajs__haj_id__posts__post_id__image_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/hajs/{haj_id}/friends/code": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Gen Friend Code */
        get: operations["gen_friend_code_api_hajs__haj_id__friends_code_get"];
        put?: never;
        /** Use Friend Code */
        post: operations["use_friend_code_api_hajs__haj_id__friends_code_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/register": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Register */
        post: operations["register_api_auth_register_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/delete": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Delete */
        delete: operations["delete_api_auth_delete_delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/new_verification_token": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** New Verif Token */
        post: operations["new_verif_token_api_auth_new_verification_token_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/verify": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Verify */
        post: operations["verify_api_auth_verify_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/token": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Token */
        post: operations["token_api_auth_token_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Logout */
        post: operations["logout_api_auth_logout_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Me */
        get: operations["me_api_auth_me_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/email": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /** Change Email */
        put: operations["change_email_api_auth_email_put"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/password": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /** Change Password */
        put: operations["change_password_api_auth_password_put"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** Body_add_haj_api_hajs_post */
        Body_add_haj_api_hajs_post: {
            /** Image */
            image: string;
            /** Pfp */
            pfp: string;
            /** Displayname */
            displayname: string;
            /** Username */
            username: string;
            /**
             * Date
             * Format: date
             */
            date: string;
            /** Size */
            size: number;
            /** Description */
            description: string;
            /** Location */
            location?: string | null;
            /** Pronouns */
            pronouns?: string | null;
            /** Gender */
            gender?: string | null;
            /** Floof */
            floof?: number | null;
            /** Squish */
            squish?: number | null;
            /** Lastwashed */
            lastwashed?: string | null;
            /** Mloftearsabsorbed */
            mloftearsabsorbed?: number | null;
        };
        /** Body_make_post_api_hajs__haj_id__posts_post */
        Body_make_post_api_hajs__haj_id__posts_post: {
            /** Image */
            image: string;
            /** Note */
            note: string;
            /** Alt Text */
            alt_text: string;
            /** Cw */
            cw?: string | null;
            /** Location */
            location?: string | null;
        };
        /** Body_patch_haj_api_hajs__haj_id__patch */
        Body_patch_haj_api_hajs__haj_id__patch: {
            /** Image */
            image?: string | null;
            /** Pfp */
            pfp?: string | null;
            /** Displayname */
            displayname?: string | null;
            /** Date */
            date?: string | null;
            /** Size */
            size?: number | null;
            /** Description */
            description?: string | null;
            /** Location */
            location?: string | null;
            /** Pronouns */
            pronouns?: string | null;
            /** Gender */
            gender?: string | null;
            /** Floof */
            floof?: number | null;
            /** Squish */
            squish?: number | null;
            /** Lastwashed */
            lastwashed?: string | null;
            /** Mloftearsabsorbed */
            mloftearsabsorbed?: number | null;
        };
        /** Body_token_api_auth_token_post */
        Body_token_api_auth_token_post: {
            /** Grant Type */
            grant_type?: string | null;
            /** Username */
            username: string;
            /**
             * Password
             * Format: password
             */
            password: string;
            /**
             * Scope
             * @default
             */
            scope: string;
            /** Client Id */
            client_id?: string | null;
            /**
             * Client Secret
             * Format: password
             */
            client_secret?: string | null;
        };
        /** EmailRequest */
        EmailRequest: {
            /** Email */
            email: string;
        };
        /** FriendCodeRequest */
        FriendCodeRequest: {
            /** Code */
            code: string;
        };
        /** FriendCodeResponse */
        FriendCodeResponse: {
            /** Status */
            status: string;
            /** Code */
            code: string;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** HajItem */
        HajItem: {
            /**
             * Uuid
             * Format: uuid4
             */
            uuid: string;
            /**
             * Human
             * Format: uuid4
             */
            human: string;
            /** Displayname */
            displayname: string;
            /** Emoji */
            emoji: string;
            /** Species */
            species: string;
            /** Username */
            username: string;
            /**
             * Date
             * Format: date
             */
            date: string;
            /** Size */
            size: number;
            /** Description */
            description: string;
            /** Location */
            location?: string | null;
            /** Pronouns */
            pronouns?: string | null;
            /** Gender */
            gender?: string | null;
            /** Floof */
            floof?: number | null;
            /** Squish */
            squish?: number | null;
            /** Lastwashed */
            lastwashed?: string | null;
            /** Mloftearsabsorbed */
            mloftearsabsorbed?: number | null;
        };
        /** HajListItem */
        HajListItem: {
            /**
             * Uuid
             * Format: uuid4
             */
            uuid: string;
            /** Displayname */
            displayname: string;
            /** Pronouns */
            pronouns?: string | null;
        };
        /** HajListResponse */
        HajListResponse: {
            /** Status */
            status: string;
            /** Hajs */
            hajs: components["schemas"]["HajListItem"][];
        };
        /** HajResponse */
        HajResponse: {
            /** Status */
            status: string;
            haj: components["schemas"]["HajItem"];
            /** Sharkeylink */
            sharkeylink: string;
            /** Sharkey */
            sharkey?: {
                [key: string]: unknown;
            } | null;
            /** Friends */
            friends?: components["schemas"]["HajListItem"][] | null;
        };
        /** NewTokenRequest */
        NewTokenRequest: {
            /**
             * Email
             * Format: email
             */
            email: string;
        };
        /** NfcInfoResponse */
        NfcInfoResponse: {
            /** Is Setup */
            is_setup: boolean;
            /** Uid */
            uid?: string | null;
            /** Counter */
            counter?: number | null;
        };
        /** NfcInserted */
        NfcInserted: {
            /** Haj Id */
            haj_id: string;
            /** Key0 */
            key0: string;
            /** Key3 */
            key3: string;
            /** Key4 */
            key4: string;
        };
        /** NfcRequest */
        NfcRequest: {
            /** Picc Data */
            picc_data: string;
            /** Cmac */
            cmac: string;
        };
        /** NfcResponse */
        NfcResponse: {
            /** Status */
            status: string;
            inserted: components["schemas"]["NfcInserted"];
        };
        /** PasswordRequest */
        PasswordRequest: {
            /** Password */
            password: string;
        };
        /** PostListItem */
        PostListItem: {
            /**
             * Id
             * Format: uuid4
             */
            id: string;
            /**
             * Haj
             * Format: uuid4
             */
            haj: string;
            /** Sharkey Id */
            sharkey_id: string;
            /** Sharkey File */
            sharkey_file: string;
            /** Text */
            text: string;
            /** Cw */
            cw: string | null;
            /** Created At */
            created_at: string | null;
        };
        /** PostListResponse */
        PostListResponse: {
            /** Status */
            status: string;
            /** Posts */
            posts: components["schemas"]["PostListItem"][];
        };
        /** ProvisionRequest */
        ProvisionRequest: {
            /** Tag Id */
            tag_id: string;
            /**
             * Haj Id
             * Format: uuid4
             */
            haj_id: string;
        };
        /** RegisterRequest */
        RegisterRequest: {
            /** Username */
            username: string;
            /**
             * Email
             * Format: email
             */
            email: string;
            /** Password */
            password: string;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
        /** VerifyRequest */
        VerifyRequest: {
            /** Token */
            token: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    test_api__get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
    nfc_auth_api_nfc_auth_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["NfcRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    provision_api_nfc_provision_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ProvisionRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["NfcResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    check_nfc_api_nfc__haj_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                haj_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["NfcInfoResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_hajs_api_hajs_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HajListResponse"];
                };
            };
        };
    };
    add_haj_api_hajs_post: {
        parameters: {
            query: {
                emoji: string;
                species: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "multipart/form-data": components["schemas"]["Body_add_haj_api_hajs_post"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    haj_info_api_hajs__haj_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                haj_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HajResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_haj_api_hajs__haj_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                haj_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    patch_haj_api_hajs__haj_id__patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                haj_id: string;
            };
            cookie?: never;
        };
        requestBody?: {
            content: {
                "multipart/form-data": components["schemas"]["Body_patch_haj_api_hajs__haj_id__patch"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_haj_image_api_hajs__haj_id__image_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                haj_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_haj_pfp_api_hajs__haj_id__pfp_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                haj_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_posts_api_hajs__haj_id__posts_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                haj_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PostListResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    make_post_api_hajs__haj_id__posts_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                haj_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "multipart/form-data": components["schemas"]["Body_make_post_api_hajs__haj_id__posts_post"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_post_image_api_hajs__haj_id__posts__post_id__image_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                haj_id: string;
                post_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    gen_friend_code_api_hajs__haj_id__friends_code_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                haj_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FriendCodeResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    use_friend_code_api_hajs__haj_id__friends_code_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                haj_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["FriendCodeRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HajResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    register_api_auth_register_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RegisterRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_api_auth_delete_delete: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
    new_verif_token_api_auth_new_verification_token_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["NewTokenRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    verify_api_auth_verify_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["VerifyRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    token_api_auth_token_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/x-www-form-urlencoded": components["schemas"]["Body_token_api_auth_token_post"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    logout_api_auth_logout_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
    me_api_auth_me_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
    change_email_api_auth_email_put: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["EmailRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    change_password_api_auth_password_put: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PasswordRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
